version: "3.7"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server/.env.production
    ports:
      - 8080:8080
    volumes:
      - ./server/dist:/app/server/dist
    networks:
      - app-network
    restart: always
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - 80:80
    restart: always
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
