version: "3.7"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - 8080
    env_file: ./server/.env.production
    ports:
      - 8080:8080
    volumes:
      - ./server/dist:/app/server/dist
    depends_on:
      - db
    networks:
      - app-network
    restart: always
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    depends_on:
      - server
    ports:
      - 3000:3000
    command: npm start
    restart: always
    networks:
      - app-network
  db:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
