name: pipeline

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    name: setup environment
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

  build:
    needs: setup
    name: build npm packages
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Restore node_modules from cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install linting dependencies
        run: npm ci --cache ~/.npm --prefer-offline

      - name: Install client dependencies
        run: cd client && npm ci --only=prod --cache ~/.npm --prefer-offline

  linter:
    needs: [setup, build]
    name: run linter and formater
    runs-on: ubuntu-latest
    steps:
      - name: Run linter
        run: npm run lint
